/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R1SuitSpiderSolitaireRouteImport } from './routes/1-suit-spider-solitaire'
import { Route as R2SuitSpiderSolitaireRouteImport } from './routes/2-suit-spider-solitaire'
import { Route as R4SuitSpiderSolitaireRouteImport } from './routes/4-suit-spider-solitaire'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddictionRouteImport } from './routes/addiction'
import { Route as BakersDozenRouteImport } from './routes/bakers-dozen'
import { Route as BakersGameRouteImport } from './routes/bakers-game'
import { Route as CanfieldRouteImport } from './routes/canfield'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as DoubleKlondikeRouteImport } from './routes/double-klondike'
import { Route as EightOffRouteImport } from './routes/eight-off'
import { Route as FortyThievesRouteImport } from './routes/forty-thieves'
import { Route as FreecellRouteImport } from './routes/freecell'
import { Route as FreecellSolitaireRouteImport } from './routes/freecell-solitaire'
import { Route as GolfRouteImport } from './routes/golf'
import { Route as KlondikeRouteImport } from './routes/klondike'
import { Route as KlondikeSolitaireRouteImport } from './routes/klondike-solitaire'
import { Route as MahjongRouteImport } from './routes/mahjong'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PyramidRouteImport } from './routes/pyramid'
import { Route as ScorpionRouteImport } from './routes/scorpion'
import { Route as SpiderRouteImport } from './routes/spider'
import { Route as SpiderSolitaireRouteImport } from './routes/spider-solitaire'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripeaksRouteImport } from './routes/tripeaks'
import { Route as Turn3SolitaireRouteImport } from './routes/turn-3-solitaire'
import { Route as VegasSolitaireRouteImport } from './routes/vegas-solitaire'
import { Route as WinPreviewRouteImport } from './routes/win-preview'
import { Route as YukonRouteImport } from './routes/yukon'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R1SuitSpiderSolitaireRoute = R1SuitSpiderSolitaireRouteImport.update({
  id: '/1-suit-spider-solitaire',
  path: '/1-suit-spider-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const R2SuitSpiderSolitaireRoute = R2SuitSpiderSolitaireRouteImport.update({
  id: '/2-suit-spider-solitaire',
  path: '/2-suit-spider-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const R4SuitSpiderSolitaireRoute = R4SuitSpiderSolitaireRouteImport.update({
  id: '/4-suit-spider-solitaire',
  path: '/4-suit-spider-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddictionRoute = AddictionRouteImport.update({
  id: '/addiction',
  path: '/addiction',
  getParentRoute: () => rootRouteImport,
} as any)
const BakersDozenRoute = BakersDozenRouteImport.update({
  id: '/bakers-dozen',
  path: '/bakers-dozen',
  getParentRoute: () => rootRouteImport,
} as any)
const BakersGameRoute = BakersGameRouteImport.update({
  id: '/bakers-game',
  path: '/bakers-game',
  getParentRoute: () => rootRouteImport,
} as any)
const CanfieldRoute = CanfieldRouteImport.update({
  id: '/canfield',
  path: '/canfield',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubleKlondikeRoute = DoubleKlondikeRouteImport.update({
  id: '/double-klondike',
  path: '/double-klondike',
  getParentRoute: () => rootRouteImport,
} as any)
const EightOffRoute = EightOffRouteImport.update({
  id: '/eight-off',
  path: '/eight-off',
  getParentRoute: () => rootRouteImport,
} as any)
const FortyThievesRoute = FortyThievesRouteImport.update({
  id: '/forty-thieves',
  path: '/forty-thieves',
  getParentRoute: () => rootRouteImport,
} as any)
const FreecellRoute = FreecellRouteImport.update({
  id: '/freecell',
  path: '/freecell',
  getParentRoute: () => rootRouteImport,
} as any)
const FreecellSolitaireRoute = FreecellSolitaireRouteImport.update({
  id: '/freecell-solitaire',
  path: '/freecell-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfRoute = GolfRouteImport.update({
  id: '/golf',
  path: '/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const KlondikeRoute = KlondikeRouteImport.update({
  id: '/klondike',
  path: '/klondike',
  getParentRoute: () => rootRouteImport,
} as any)
const KlondikeSolitaireRoute = KlondikeSolitaireRouteImport.update({
  id: '/klondike-solitaire',
  path: '/klondike-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MahjongRoute = MahjongRouteImport.update({
  id: '/mahjong',
  path: '/mahjong',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PyramidRoute = PyramidRouteImport.update({
  id: '/pyramid',
  path: '/pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorpionRoute = ScorpionRouteImport.update({
  id: '/scorpion',
  path: '/scorpion',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiderRoute = SpiderRouteImport.update({
  id: '/spider',
  path: '/spider',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiderSolitaireRoute = SpiderSolitaireRouteImport.update({
  id: '/spider-solitaire',
  path: '/spider-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripeaksRoute = TripeaksRouteImport.update({
  id: '/tripeaks',
  path: '/tripeaks',
  getParentRoute: () => rootRouteImport,
} as any)
const Turn3SolitaireRoute = Turn3SolitaireRouteImport.update({
  id: '/turn-3-solitaire',
  path: '/turn-3-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const VegasSolitaireRoute = VegasSolitaireRouteImport.update({
  id: '/vegas-solitaire',
  path: '/vegas-solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const WinPreviewRoute = WinPreviewRouteImport.update({
  id: '/win-preview',
  path: '/win-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const YukonRoute = YukonRouteImport.update({
  id: '/yukon',
  path: '/yukon',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1-suit-spider-solitaire': typeof R1SuitSpiderSolitaireRoute
  '/2-suit-spider-solitaire': typeof R2SuitSpiderSolitaireRoute
  '/4-suit-spider-solitaire': typeof R4SuitSpiderSolitaireRoute
  '/about': typeof AboutRoute
  '/addiction': typeof AddictionRoute
  '/bakers-dozen': typeof BakersDozenRoute
  '/bakers-game': typeof BakersGameRoute
  '/canfield': typeof CanfieldRoute
  '/clock': typeof ClockRoute
  '/double-klondike': typeof DoubleKlondikeRoute
  '/eight-off': typeof EightOffRoute
  '/forty-thieves': typeof FortyThievesRoute
  '/freecell': typeof FreecellRoute
  '/freecell-solitaire': typeof FreecellSolitaireRoute
  '/golf': typeof GolfRoute
  '/klondike': typeof KlondikeRoute
  '/klondike-solitaire': typeof KlondikeSolitaireRoute
  '/mahjong': typeof MahjongRoute
  '/privacy': typeof PrivacyRoute
  '/pyramid': typeof PyramidRoute
  '/scorpion': typeof ScorpionRoute
  '/spider': typeof SpiderRoute
  '/spider-solitaire': typeof SpiderSolitaireRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tripeaks': typeof TripeaksRoute
  '/turn-3-solitaire': typeof Turn3SolitaireRoute
  '/vegas-solitaire': typeof VegasSolitaireRoute
  '/win-preview': typeof WinPreviewRoute
  '/yukon': typeof YukonRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1-suit-spider-solitaire': typeof R1SuitSpiderSolitaireRoute
  '/2-suit-spider-solitaire': typeof R2SuitSpiderSolitaireRoute
  '/4-suit-spider-solitaire': typeof R4SuitSpiderSolitaireRoute
  '/about': typeof AboutRoute
  '/addiction': typeof AddictionRoute
  '/bakers-dozen': typeof BakersDozenRoute
  '/bakers-game': typeof BakersGameRoute
  '/canfield': typeof CanfieldRoute
  '/clock': typeof ClockRoute
  '/double-klondike': typeof DoubleKlondikeRoute
  '/eight-off': typeof EightOffRoute
  '/forty-thieves': typeof FortyThievesRoute
  '/freecell': typeof FreecellRoute
  '/freecell-solitaire': typeof FreecellSolitaireRoute
  '/golf': typeof GolfRoute
  '/klondike': typeof KlondikeRoute
  '/klondike-solitaire': typeof KlondikeSolitaireRoute
  '/mahjong': typeof MahjongRoute
  '/privacy': typeof PrivacyRoute
  '/pyramid': typeof PyramidRoute
  '/scorpion': typeof ScorpionRoute
  '/spider': typeof SpiderRoute
  '/spider-solitaire': typeof SpiderSolitaireRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tripeaks': typeof TripeaksRoute
  '/turn-3-solitaire': typeof Turn3SolitaireRoute
  '/vegas-solitaire': typeof VegasSolitaireRoute
  '/win-preview': typeof WinPreviewRoute
  '/yukon': typeof YukonRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1-suit-spider-solitaire': typeof R1SuitSpiderSolitaireRoute
  '/2-suit-spider-solitaire': typeof R2SuitSpiderSolitaireRoute
  '/4-suit-spider-solitaire': typeof R4SuitSpiderSolitaireRoute
  '/about': typeof AboutRoute
  '/addiction': typeof AddictionRoute
  '/bakers-dozen': typeof BakersDozenRoute
  '/bakers-game': typeof BakersGameRoute
  '/canfield': typeof CanfieldRoute
  '/clock': typeof ClockRoute
  '/double-klondike': typeof DoubleKlondikeRoute
  '/eight-off': typeof EightOffRoute
  '/forty-thieves': typeof FortyThievesRoute
  '/freecell': typeof FreecellRoute
  '/freecell-solitaire': typeof FreecellSolitaireRoute
  '/golf': typeof GolfRoute
  '/klondike': typeof KlondikeRoute
  '/klondike-solitaire': typeof KlondikeSolitaireRoute
  '/mahjong': typeof MahjongRoute
  '/privacy': typeof PrivacyRoute
  '/pyramid': typeof PyramidRoute
  '/scorpion': typeof ScorpionRoute
  '/spider': typeof SpiderRoute
  '/spider-solitaire': typeof SpiderSolitaireRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tripeaks': typeof TripeaksRoute
  '/turn-3-solitaire': typeof Turn3SolitaireRoute
  '/vegas-solitaire': typeof VegasSolitaireRoute
  '/win-preview': typeof WinPreviewRoute
  '/yukon': typeof YukonRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1-suit-spider-solitaire'
    | '/2-suit-spider-solitaire'
    | '/4-suit-spider-solitaire'
    | '/about'
    | '/addiction'
    | '/bakers-dozen'
    | '/bakers-game'
    | '/canfield'
    | '/clock'
    | '/double-klondike'
    | '/eight-off'
    | '/forty-thieves'
    | '/freecell'
    | '/freecell-solitaire'
    | '/golf'
    | '/klondike'
    | '/klondike-solitaire'
    | '/mahjong'
    | '/privacy'
    | '/pyramid'
    | '/scorpion'
    | '/spider'
    | '/spider-solitaire'
    | '/stats'
    | '/terms'
    | '/tripeaks'
    | '/turn-3-solitaire'
    | '/vegas-solitaire'
    | '/win-preview'
    | '/yukon'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1-suit-spider-solitaire'
    | '/2-suit-spider-solitaire'
    | '/4-suit-spider-solitaire'
    | '/about'
    | '/addiction'
    | '/bakers-dozen'
    | '/bakers-game'
    | '/canfield'
    | '/clock'
    | '/double-klondike'
    | '/eight-off'
    | '/forty-thieves'
    | '/freecell'
    | '/freecell-solitaire'
    | '/golf'
    | '/klondike'
    | '/klondike-solitaire'
    | '/mahjong'
    | '/privacy'
    | '/pyramid'
    | '/scorpion'
    | '/spider'
    | '/spider-solitaire'
    | '/stats'
    | '/terms'
    | '/tripeaks'
    | '/turn-3-solitaire'
    | '/vegas-solitaire'
    | '/win-preview'
    | '/yukon'
    | '/guides/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/1-suit-spider-solitaire'
    | '/2-suit-spider-solitaire'
    | '/4-suit-spider-solitaire'
    | '/about'
    | '/addiction'
    | '/bakers-dozen'
    | '/bakers-game'
    | '/canfield'
    | '/clock'
    | '/double-klondike'
    | '/eight-off'
    | '/forty-thieves'
    | '/freecell'
    | '/freecell-solitaire'
    | '/golf'
    | '/klondike'
    | '/klondike-solitaire'
    | '/mahjong'
    | '/privacy'
    | '/pyramid'
    | '/scorpion'
    | '/spider'
    | '/spider-solitaire'
    | '/stats'
    | '/terms'
    | '/tripeaks'
    | '/turn-3-solitaire'
    | '/vegas-solitaire'
    | '/win-preview'
    | '/yukon'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1SuitSpiderSolitaireRoute: typeof R1SuitSpiderSolitaireRoute
  R2SuitSpiderSolitaireRoute: typeof R2SuitSpiderSolitaireRoute
  R4SuitSpiderSolitaireRoute: typeof R4SuitSpiderSolitaireRoute
  AboutRoute: typeof AboutRoute
  AddictionRoute: typeof AddictionRoute
  BakersDozenRoute: typeof BakersDozenRoute
  BakersGameRoute: typeof BakersGameRoute
  CanfieldRoute: typeof CanfieldRoute
  ClockRoute: typeof ClockRoute
  DoubleKlondikeRoute: typeof DoubleKlondikeRoute
  EightOffRoute: typeof EightOffRoute
  FortyThievesRoute: typeof FortyThievesRoute
  FreecellRoute: typeof FreecellRoute
  FreecellSolitaireRoute: typeof FreecellSolitaireRoute
  GolfRoute: typeof GolfRoute
  KlondikeRoute: typeof KlondikeRoute
  KlondikeSolitaireRoute: typeof KlondikeSolitaireRoute
  MahjongRoute: typeof MahjongRoute
  PrivacyRoute: typeof PrivacyRoute
  PyramidRoute: typeof PyramidRoute
  ScorpionRoute: typeof ScorpionRoute
  SpiderRoute: typeof SpiderRoute
  SpiderSolitaireRoute: typeof SpiderSolitaireRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  TripeaksRoute: typeof TripeaksRoute
  Turn3SolitaireRoute: typeof Turn3SolitaireRoute
  VegasSolitaireRoute: typeof VegasSolitaireRoute
  WinPreviewRoute: typeof WinPreviewRoute
  YukonRoute: typeof YukonRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1-suit-spider-solitaire': {
      id: '/1-suit-spider-solitaire'
      path: '/1-suit-spider-solitaire'
      fullPath: '/1-suit-spider-solitaire'
      preLoaderRoute: typeof R1SuitSpiderSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2-suit-spider-solitaire': {
      id: '/2-suit-spider-solitaire'
      path: '/2-suit-spider-solitaire'
      fullPath: '/2-suit-spider-solitaire'
      preLoaderRoute: typeof R2SuitSpiderSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4-suit-spider-solitaire': {
      id: '/4-suit-spider-solitaire'
      path: '/4-suit-spider-solitaire'
      fullPath: '/4-suit-spider-solitaire'
      preLoaderRoute: typeof R4SuitSpiderSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addiction': {
      id: '/addiction'
      path: '/addiction'
      fullPath: '/addiction'
      preLoaderRoute: typeof AddictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakers-dozen': {
      id: '/bakers-dozen'
      path: '/bakers-dozen'
      fullPath: '/bakers-dozen'
      preLoaderRoute: typeof BakersDozenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakers-game': {
      id: '/bakers-game'
      path: '/bakers-game'
      fullPath: '/bakers-game'
      preLoaderRoute: typeof BakersGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canfield': {
      id: '/canfield'
      path: '/canfield'
      fullPath: '/canfield'
      preLoaderRoute: typeof CanfieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/double-klondike': {
      id: '/double-klondike'
      path: '/double-klondike'
      fullPath: '/double-klondike'
      preLoaderRoute: typeof DoubleKlondikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eight-off': {
      id: '/eight-off'
      path: '/eight-off'
      fullPath: '/eight-off'
      preLoaderRoute: typeof EightOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forty-thieves': {
      id: '/forty-thieves'
      path: '/forty-thieves'
      fullPath: '/forty-thieves'
      preLoaderRoute: typeof FortyThievesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freecell': {
      id: '/freecell'
      path: '/freecell'
      fullPath: '/freecell'
      preLoaderRoute: typeof FreecellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freecell-solitaire': {
      id: '/freecell-solitaire'
      path: '/freecell-solitaire'
      fullPath: '/freecell-solitaire'
      preLoaderRoute: typeof FreecellSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf': {
      id: '/golf'
      path: '/golf'
      fullPath: '/golf'
      preLoaderRoute: typeof GolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klondike': {
      id: '/klondike'
      path: '/klondike'
      fullPath: '/klondike'
      preLoaderRoute: typeof KlondikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klondike-solitaire': {
      id: '/klondike-solitaire'
      path: '/klondike-solitaire'
      fullPath: '/klondike-solitaire'
      preLoaderRoute: typeof KlondikeSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahjong': {
      id: '/mahjong'
      path: '/mahjong'
      fullPath: '/mahjong'
      preLoaderRoute: typeof MahjongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyramid': {
      id: '/pyramid'
      path: '/pyramid'
      fullPath: '/pyramid'
      preLoaderRoute: typeof PyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorpion': {
      id: '/scorpion'
      path: '/scorpion'
      fullPath: '/scorpion'
      preLoaderRoute: typeof ScorpionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spider': {
      id: '/spider'
      path: '/spider'
      fullPath: '/spider'
      preLoaderRoute: typeof SpiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spider-solitaire': {
      id: '/spider-solitaire'
      path: '/spider-solitaire'
      fullPath: '/spider-solitaire'
      preLoaderRoute: typeof SpiderSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tripeaks': {
      id: '/tripeaks'
      path: '/tripeaks'
      fullPath: '/tripeaks'
      preLoaderRoute: typeof TripeaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turn-3-solitaire': {
      id: '/turn-3-solitaire'
      path: '/turn-3-solitaire'
      fullPath: '/turn-3-solitaire'
      preLoaderRoute: typeof Turn3SolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegas-solitaire': {
      id: '/vegas-solitaire'
      path: '/vegas-solitaire'
      fullPath: '/vegas-solitaire'
      preLoaderRoute: typeof VegasSolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/win-preview': {
      id: '/win-preview'
      path: '/win-preview'
      fullPath: '/win-preview'
      preLoaderRoute: typeof WinPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yukon': {
      id: '/yukon'
      path: '/yukon'
      fullPath: '/yukon'
      preLoaderRoute: typeof YukonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1SuitSpiderSolitaireRoute: R1SuitSpiderSolitaireRoute,
  R2SuitSpiderSolitaireRoute: R2SuitSpiderSolitaireRoute,
  R4SuitSpiderSolitaireRoute: R4SuitSpiderSolitaireRoute,
  AboutRoute: AboutRoute,
  AddictionRoute: AddictionRoute,
  BakersDozenRoute: BakersDozenRoute,
  BakersGameRoute: BakersGameRoute,
  CanfieldRoute: CanfieldRoute,
  ClockRoute: ClockRoute,
  DoubleKlondikeRoute: DoubleKlondikeRoute,
  EightOffRoute: EightOffRoute,
  FortyThievesRoute: FortyThievesRoute,
  FreecellRoute: FreecellRoute,
  FreecellSolitaireRoute: FreecellSolitaireRoute,
  GolfRoute: GolfRoute,
  KlondikeRoute: KlondikeRoute,
  KlondikeSolitaireRoute: KlondikeSolitaireRoute,
  MahjongRoute: MahjongRoute,
  PrivacyRoute: PrivacyRoute,
  PyramidRoute: PyramidRoute,
  ScorpionRoute: ScorpionRoute,
  SpiderRoute: SpiderRoute,
  SpiderSolitaireRoute: SpiderSolitaireRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  TripeaksRoute: TripeaksRoute,
  Turn3SolitaireRoute: Turn3SolitaireRoute,
  VegasSolitaireRoute: VegasSolitaireRoute,
  WinPreviewRoute: WinPreviewRoute,
  YukonRoute: YukonRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
